mysite/food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path("", views.IndexClassView.as_view(), name="index"),
    path("<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("item/", views.item, name="item"),
    # add items
    path('add/', views.CreateItem.as_view(), name="create-item"),
    # edit
    path("update/<int:id>/", views.update_item, name="update-item"),
    # delete
    path("delete/<int:id>/", views.delete_item, name="delete-item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.decorators import login_required
# from users.views import ProfileView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path("profile/", user_views.profilepage, name="profile")
    # path('profile/', login_required(ProfileView.as_view()), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_img = models.CharField(
        max_length=500, default="https://luigispizzakenosha.com/wp-content/uploads/placeholder.png")

    def __str__(self) -> str:
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',
                              upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item


class ItemCreationForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", 'email', "password1", "password2"]

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import Item
from .forms import ItemCreationForm

# Create your views here.


# def index(request):
#     item_list = Item.objects.all()
#     return render(request, "food/index.html", {
#         "item_list": item_list,
#     })

class IndexClassView(ListView):
    template_name = "food/index.html"
    model = Item
    context_object_name = "item_list"


def item(request):
    return HttpResponse("This is an item view")


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     return render(request, "food/detail.html", {
#         "item": item,
#     })

class FoodDetail(DetailView):
    template_name = "food/detail.html"
    model = Item


def create_item(request):
    form = ItemCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, "food/item-form.html", {
        "form": form,
    })


class CreateItem(CreateView):
    template_name = "food/item-form.html"
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_img"]

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemCreationForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "food/item-form.html", {
        "item": item,
        "form": form,
    })


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect("food:index")

    return render(request, "food/item-delete.html", {
        "item": item
    })

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
from django.views.generic import TemplateView

# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Welcome {
                             username}, your account has been created")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {
        "form": form
    })


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')


class ProfileView(TemplateView):
    template_name = 'users/profile.html'

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark p-3">
        <a href="/food/" class="navbar-brand ">Food App</a>
        <div class="navbar">
            <a href="{% url "food:create-item" %}" class="nav-item nav-link text-light p-3">Add Item</a>
            <a href="#" class="nav-item nav-link text-light p-3">Delete Item</a>
            <a href="#" class="nav-item nav-link text-light p-3">View Item</a>

            {% if user.is_authenticated %}
                <a href="{% url "profile" %}" class="nav-item nav-link text-light p-3">Profile</a>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-item nav-link text-light p-3">Log Out</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link text-light p-3">Login</a>
            {% endif %}
            
            
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock  %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends "food/base.html" %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_img }}" alt="" class="card" style="height: 300px;">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <p>{{ object.item_desc }}</p>
            <p>${{ object.item_price }}</p>
            <a href="{% url "food:delete-item" item.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/food/templates/food/index.html
{% extends "food/base.html" %}

{% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card-img" style="height: 150px;" src="{{ item.item_img }}">
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                <h6>Created by: {{ item.user_name }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>      
    {% endfor %}
{% endblock  %}

mysite/food/templates/food/item-delete.html
<form action="" method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends "food/base.html" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">Add item</div>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-outline-info m-3" type="submit">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

mysite/users/templates/users/login.html
{% extends "food/base.html" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">Login</div>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-outline-info m-3" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

mysite/users/templates/users/logout.html
{% extends "food/base.html" %}

{% block body %}
    <h1>You have been logged out</h1>
{% endblock  %}

mysite/users/templates/users/profile.html
{% extends "food/base.html" %}

{% block body %}
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url  }}" alt="">
{% endblock  %}

mysite/users/templates/users/register.html
{% extends "food/base.html" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">Register</div>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-outline-info m-3" type="submit">Signup</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}